FROM python:3.13-slim

RUN pip install -U pip
RUN pip install flask gunicorn pipenv

WORKDIR /app

ENV MLFLOW_TRACKING_URI=http://127.0.0.1:5000

COPY ["Pipfile", "Pipfile.lock", "./"]

RUN pipenv install --system --deploy

COPY ["predict.py", "intro_lm.bin", "./"]

EXPOSE 9696

ENTRYPOINT [ "gunicorn", "--bind=0.0.0.0:9696", "predict:app" ]
