{
 "title": "Wine Quality Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  prediction_drift\nFROM drift_metrics\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  num_drifted_columns\nFROM drift_metrics\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Share of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  share_missing_values * 100 as value\nFROM drift_metrics\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Fare Amount Quantile Comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  fare_amount_quantile_current as \"Current\",\n  fare_amount_quantile_reference as \"Reference\"\nFROM drift_metrics\nORDER BY 1"
    }
   ]
  }
 ]
}