FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

ENV MLFLOW_TRACKING_URI=http://127.0.0.1:5000

COPY starter.py .

RUN pip install pandas pyarrow scikit-learn

ENTRYPOINT ["python3", "starter.py", "2023", "04"]
