FROM python:3.9-slim

RUN pip install mlflow==2.12.1

EXPOSE 5005

WORKDIR /home/mlflow_data

CMD [\
    "mlflow", "server", \
    "--backend-store-uri", "sqlite:///mlflow.db", \
    "--host", "0.0.0.0", \
    "--port", "5005" \
]
