{
 "title": "New dashboard",
 "time": { "from": "2024-03-01T00:00:00.000Z", "to": "2024-03-04T00:00:00.000Z" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM drift_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare Amount Quantile (Median)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT fare_amount_quantile_current, fare_amount_quantile_reference, \"timestamp\" FROM drift_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number Of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM drift_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share Of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM drift_metrics LIMIT 50 "
    }
   ]
  }
 ]
}