name: CI Pipeline

on:
  push:
    branches: [ projects ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        
    - name: Run unit tests
      working-directory: projects
      run: |
        pipenv run python -m pytest tests/
        
    - name: Check code formatting with Black
      working-directory: projects
      run: |
        pipenv run black  .
        
    - name: Check imports with isort
      run: |
        pipenv run isort  .
        
    - name: Format code if checks fail
      if: failure()
      run: |
        pipenv run black .
        pipenv run isort .
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -am "Apply automatic formatting" || true
        git push || true
